### PR TITLE
re-bind ozwDriver events if neccessary

### PR DESCRIPTION
**Pull request by hobbyquaker**
Had the problem that the ozwDriver event bindings where lost when I deployed in Node-RED. Solved by introducing a ozwBoundEvents variable to keep track of the bind state and moving the binding outside the OpenZWave initializiation.

### CODE REVIEW

**Comment by ekarak** [comment]
thank you!

**Comment by hobbyquaker** [comment]
you're welcome :-) And thank you for your work on OpenZWave!

**Comment by dgmltn** [comment]
@ekarak do you have plans to make a new npm release with this update?

**Comment by ekarak** [comment]
apologies, I forgot:) version 1.2.4 was just released

**Pull request merged**
